import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { getAll } from './cityAPI';

const initialState = {
  all: [],
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(fetchAll())`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchAll = createAsyncThunk(
  'ficty/fetchAll',
  async () => {
    const response = await getAll();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const citySlice = createSlice({
  name: 'city',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchAll.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchAll.fulfilled, (state, action) => {
        state.status = 'idle';
        state.all = [...state.all, ...action.payload];
      });
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file.
export const selectCities = (state) => state.city.all;


export default citySlice.reducer;
